
#line 3 "jive.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 161
#define YY_END_OF_BUFFER 162
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[569] =
    {   0,
        0,    0,  162,  159,  160,  159,   55,  159,  159,  159,
      159,  159,  159,  159,  159,  159,  159,  159,  159,  159,
      159,  159,  159,  159,  159,  159,  159,  159,  159,  159,
      159,  159,  159,  159,  159,  159,  159,  159,  159,  159,
      159,  159,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  157,    0,    0,    0,    0,   89,
        0,    0,    0,    0,    0,   28,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   29,    0,    0,    0,    0,    0,    0,

        0,    0,   30,    0,    0,    0,    0,    0,    0,    0,
        0,   31,    0,    0,    0,    0,    0,    0,    0,    0,
       69,    0,    0,    0,    0,   32,    0,    0,    0,    0,
        0,    0,    0,   88,    0,   33,    0,    0,    0,    0,
        0,    0,    0,   34,    0,    0,    0,    0,    0,    0,
      130,   91,    0,    0,    0,    0,    0,    0,    0,  108,
        0,    0,    0,    0,    0,    0,    0,  129,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   26,    0,
        0,    0,    0,    0,    0,    0,  158,    0,   82,    0,
        0,    0,    0,    0,  146,    0,    0,    0,  145,    0,

        0,    0,   56,    0,    0,    0,  110,    0,    0,    0,
        0,  101,  105,  106,    0,    0,    0,    0,    0,    0,
        0,   78,    0,    0,    0,   90,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  122,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      127,    0,    0,    0,    0,    0,    0,   81,    0,    0,
        0,    0,    0,    0,    0,    0,  124,    0,    0,    0,
      107,    0,   37,   52,    0,  149,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   92,  154,    0,    0,   27,

        0,   41,    0,    0,   35,    6,  144,    0,   76,    0,
        0,    0,    0,    0,    0,    0,  104,    0,  151,  140,
        0,    0,    0,    0,  117,    0,  155,    0,    0,    1,
        0,   15,    0,   77,    0,   23,  118,    0,    0,  132,
       51,    0,    0,    0,   14,    0,    0,   72,    0,  109,
        0,  131,    0,    0,    0,   66,   64,  100,    0,    0,
      123,    0,    0,    0,    0,    2,    0,    0,    0,   36,
        0,   12,  134,   93,    5,  103,    0,  143,    0,    0,
        0,    0,    0,    0,    0,   75,    0,    0,    0,    0,
        0,   57,    0,   59,   95,   47,   25,   21,  113,    0,

        0,    0,   67,   86,   48,    0,  121,  128,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    4,    0,    0,
      156,    0,    0,    0,   13,   58,    0,   83,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  125,    0,  102,
        0,    0,   16,  135,  119,    0,  153,    0,    0,    0,
        0,  147,    0,    0,    0,    7,    0,    0,    0,  150,
       62,   39,   22,  112,   87,    0,   80,    0,    0,    0,
        0,   60,   54,  114,   61,    0,    0,    0,    0,    0,
       98,   18,    0,   42,    0,   79,  136,    0,    0,    0,
       20,   17,    0,  138,   40,    0,    0,    0,    0,   43,

        0,    0,    0,    0,    0,   65,   84,    0,  139,    0,
        0,   19,    0,    0,    0,    0,   97,    0,    0,    0,
        0,   63,   85,   74,   10,    8,   99,   44,   73,    0,
        0,    0,    0,   50,   49,   70,   11,  111,    0,    9,
      120,    3,    0,  148,  133,  141,    0,    0,   94,   46,
        0,  126,    0,   68,  137,    0,  152,    0,  142,    0,
       45,   96,   53,    0,   24,   38,   71,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    1,    1,    1,    1,    1,    5,    1,
        1,    1,    1,    1,    6,    7,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    8,    9,    1,    1,    1,    1,
        1,   10,   11,    1,    1,    1,   12,   13,    1,    1,
        1,    1,   14,   15,   16,   17,   18,   19,   20,    1,
        1,    1,    1,    1,    1,    1,   21,   22,   23,   24,

       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
       45,   46,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[47] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[569] =
    {   0,
        0,    0,  602,  603,  603,   44,  603,  566,  575,  570,
       48,  573,  556,  568,  582,  586,  568,  557,   57,   91,
      556,   71,   55,   72,   19,  569,   74,   95,   23,  560,
       96,   98,   25,   90,  581,  110,  119,   84,  580,  121,
      123,  579,  157,  582,  131,   43,  117,  118,  546,  558,
      561,  138,  552,  136,   24,  559,  554,   64,  543,  541,
      551,  550,   88,  551,  603,  552,  551,  527,  532,  603,
      558,  549,  535,  525,  525,  603,  526,  560,  537,  529,
      129,  143,  533,  132,  534,  513,  524,  516,  534,  530,
       16,  524,  512,  603,  548,  134,  151,  151,  521,  511,

      159,  145,  603,  145,  545,  526,  504,  506,  510,  119,
      512,  603,  515,  158,  517,  501,  506,  515,  516,  511,
      603,  499,  496,  501,  497,  603,  503,  496,  508,  167,
      490,  487,  172,  603,  491,  603,  496,  172,  492,  494,
      490,  488,  491,  603,  478,  185,  182,  155,  497,  496,
      603,  513,  482,  489,  186,  492,  181,  479,  471,  487,
      474,  468,  181,  504,  481,  471,  470,  603,  476,  475,
      461,  479,  464,  460,  494,  493,  457,  456,  603,  487,
      471,  458,  458,  460,  463,  468,  603,  454,  203,  457,
      455,  449,  210,  461,  603,  450,  440,  458,  603,  447,

      438,  455,  603,  191,  447,  450,  603,  468,  438,  429,
      442,  603,  603,  603,  444,  429,  190,  429,  441,  433,
      440,  460,  437,  423,  435,  603,  418,  424,  425,  431,
      415,  430,  410,  409,  426,  429,  428,  419,  422,  417,
      420,  419,  398,  408,  416,  189,  411,  412,  403,  413,
      404,  410,  394,  408,  404,  406,  399,  395,  384,  387,
      603,  401,  393,  384,  391,  204,  382,  218,  398,  382,
      379,  383,  414,  395,  386,  391,  603,  410,  387,  408,
      603,  377,  603,  603,  406,  603,  405,  404,  221,  368,
      378,  376,  379,  377,  372,  397,  603,  354,  373,  603,

      356,  603,  367,  372,  603,  603,  603,  356,  603,  368,
      365,  356,  356,  384,  349,  362,  603,  345,  603,  603,
      354,  381,  342,  357,  603,  341,  603,  355,  354,  603,
      338,  603,  355,  603,  342,  603,  603,  335,  336,  603,
      223,  335,  337,  342,  603,  367,  366,  603,  334,  603,
      321,  603,  343,  332,  341,  603,  603,  603,  228,  325,
      603,  327,  338,  322,  324,  603,  326,  317,  353,  603,
      330,  315,  324,  603,  603,  229,  314,  603,  326,  347,
      315,  314,  322,  308,  318,  603,  305,  298,  301,  316,
      309,  336,  335,  334,  603,  333,  603,  603,  603,  332,

      299,  308,  603,  603,  603,  298,  603,  603,  292,  309,
      308,  303,  324,  298,  285,  289,  283,  603,  282,  282,
      603,  285,  279,  315,  603,  603,  314,  603,  295,  291,
      279,  279,  272,  306,  285,  269,  287,  603,  272,  603,
      277,  284,  603,  603,  603,  280,  603,  269,  277,  280,
      268,  603,  271,  263,  294,  603,  262,  255,  291,  603,
      603,  265,  603,  603,  603,  267,  603,  251,  255,  250,
      246,  603,  284,  603,  603,  248,  258,  259,  249,  248,
      603,  603,  241,  603,  240,  603,  603,  254,  236,  252,
      603,  603,  244,  603,  603,  242,  239,  233,  248,  603,

      237,  244,  235,  233,  263,  603,  603,  232,  603,  235,
      237,  603,  235,  226,  219,  237,  603,  252,  213,  226,
      225,  603,  603,  603,  603,  603,  603,  603,  603,  224,
      210,  215,  221,  603,  603,  603,  603,  603,  220,  603,
      603,  603,  209,  603,  603,  603,  207,  198,  236,  200,
      234,  603,  198,  603,  603,  201,  603,  207,  603,  208,
      603,  162,  603,  115,  603,  603,  603,  603
    } ;

static yyconst flex_int16_t yy_def[569] =
    {   0,
      568,    1,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,

      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,

      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,

      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,

      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,

      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,    0
    } ;

static yyconst flex_int16_t yy_nxt[650] =
    {   0,
        4,    5,    6,    7,    4,    8,    4,    4,    9,   10,
       11,   12,    4,   13,   14,   15,   16,   17,    4,   18,
       19,   20,   21,   22,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   34,   35,   35,   36,   37,
       38,   39,   40,    4,   41,   42,   43,  100,  169,  208,
       66,  109,  170,  101,   44,  119,  110,   93,  209,   75,
      120,   94,  121,   76,   45,   46,   47,  155,   48,   49,
       50,   51,   52,   88,  156,   53,   54,   55,   94,   56,
      103,   57,   58,   59,   60,   61,   62,   67,   77,   78,
      136,  173,   95,  179,   79,   89,   80,   76,   96,   90,

       97,  103,  112,  174,  112,   91,   98,  104,   92,   99,
      122,   81,  105,  106,  123,   82,  113,  137,  117,   83,
      114,  132,  180,  107,  124,   84,  118,  125,   85,  144,
      115,   86,  127,  152,  128,  108,  116,  157,  159,  133,
      151,  138,  129,  233,  130,  139,  134,  135,  140,  141,
      131,  158,  195,  234,  567,  142,  166,  145,  143,   43,
      167,  160,  153,  197,  562,  198,  200,  196,  154,  213,
      201,  226,  214,  224,  227,  270,  164,  146,  147,  148,
      168,  149,  215,   50,  150,  217,  225,  152,  216,  158,
       55,  218,   56,  221,   57,   58,   59,  237,  222,  252,

      223,  238,  256,  257,  253,  260,  269,  308,  274,  361,
      261,  262,  313,  156,  277,  322,  153,  275,  278,  284,
      285,  332,  384,  399,  381,  433,  323,  362,  382,  333,
      445,  458,  566,  565,  564,  563,  562,  561,  549,  560,
      309,  559,  558,  314,  557,  556,  555,  554,  553,  552,
      551,  385,  446,  550,  549,  386,  434,  548,  547,  400,
      546,  545,  544,  543,  542,  541,  540,  459,  539,  538,
      537,  536,  535,  534,  533,  532,  531,  530,  529,  528,
      527,  526,  525,  524,  523,  522,  473,  521,  520,  519,
      518,  517,  516,  515,  514,  513,  512,  511,  510,  509,

      508,  507,  506,  505,  504,  503,  502,  501,  500,  499,
      498,  497,  496,  495,  494,  493,  492,  491,  490,  489,
      488,  487,  486,  485,  484,  483,  482,  481,  480,  479,
      478,  477,  476,  475,  474,  396,  394,  473,  392,  472,
      471,  470,  469,  468,  467,  466,  465,  464,  463,  462,
      461,  460,  457,  456,  455,  454,  453,  452,  451,  450,
      449,  448,  447,  444,  443,  442,  441,  440,  439,  438,
      437,  436,  435,  432,  431,  430,  429,  428,  427,  426,
      425,  424,  423,  422,  421,  420,  419,  418,  417,  416,
      415,  414,  413,  412,  411,  410,  409,  408,  407,  296,

      406,  405,  404,  403,  402,  401,  398,  397,  396,  395,
      394,  393,  392,  391,  390,  389,  388,  387,  285,  278,
      274,  383,  380,  379,  378,  377,  376,  375,  374,  373,
      372,  371,  370,  369,  368,  367,  366,  365,  364,  363,
      360,  359,  358,  357,  356,  355,  354,  353,  352,  351,
      350,  349,  348,  347,  346,  345,  344,  343,  342,  341,
      340,  339,  338,  337,  336,  335,  334,  331,  330,  329,
      328,  327,  326,  325,  324,  321,  320,  319,  318,  317,
      316,  315,  312,  311,  310,  307,  306,  305,  304,  303,
      302,  301,  300,  299,  298,  297,  296,  295,  294,  293,

      292,  291,  290,  289,  288,  287,  286,  283,  282,  281,
      280,  279,  276,  273,  272,  152,  271,  159,  268,  267,
      266,  265,  264,  263,  259,  258,  255,  254,  251,  250,
      249,  248,  247,  246,  245,  244,  243,  242,  241,  240,
      239,  236,  235,  232,  231,  230,  229,  228,  220,  219,
      212,  211,  210,  207,  206,  205,  204,  203,  202,  199,
      194,  193,  192,  191,  190,  189,  188,  187,  186,  185,
      184,  183,  182,  181,  178,  177,  176,  175,  172,  171,
      165,  163,  162,  161,  151,  144,  136,  126,  111,  102,
       87,   74,   73,   72,   71,   70,   69,   68,   65,   64,

       63,  568,    3,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568
    } ;

static yyconst flex_int16_t yy_chk[650] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    6,   25,   55,   91,
       11,   29,   55,   25,    6,   33,   29,   23,   91,   19,
       33,   23,   33,   19,    6,    6,    6,   46,    6,    6,
        6,    6,    6,   22,   46,    6,    6,    6,   24,    6,
       27,    6,    6,    6,    6,    6,    6,   11,   19,   19,
       38,   58,   23,   63,   19,   22,   19,   20,   23,   22,

       24,   28,   31,   58,   32,   22,   24,   27,   22,   24,
       34,   20,   27,   27,   34,   20,   31,   38,   32,   20,
       31,   37,   63,   28,   34,   20,   32,   34,   20,   41,
       31,   20,   36,   45,   36,   28,   31,   47,   48,   37,
       52,   40,   36,  110,   36,   40,   37,   37,   40,   40,
       36,   47,   81,  110,  564,   40,   54,   41,   40,   43,
       54,   48,   45,   82,  562,   82,   84,   81,   45,   96,
       84,  104,   96,  102,  104,  148,   52,   43,   43,   43,
       54,   43,   97,   43,   43,   98,  102,  146,   97,  148,
       43,   98,   43,  101,   43,   43,   43,  114,  101,  130,

      101,  114,  133,  133,  130,  138,  147,  189,  155,  246,
      138,  138,  193,  147,  157,  204,  146,  155,  157,  163,
      163,  217,  268,  289,  266,  341,  204,  246,  266,  217,
      359,  376,  560,  558,  556,  553,  551,  550,  549,  548,
      189,  547,  543,  193,  539,  533,  532,  531,  530,  521,
      520,  268,  359,  519,  518,  268,  341,  516,  515,  289,
      514,  513,  511,  510,  508,  505,  504,  376,  503,  502,
      501,  499,  498,  497,  496,  493,  490,  489,  488,  485,
      483,  480,  479,  478,  477,  476,  473,  471,  470,  469,
      468,  466,  462,  459,  458,  457,  455,  454,  453,  451,

      450,  449,  448,  446,  442,  441,  439,  437,  436,  435,
      434,  433,  432,  431,  430,  429,  427,  424,  423,  422,
      420,  419,  417,  416,  415,  414,  413,  412,  411,  410,
      409,  406,  402,  401,  400,  396,  394,  393,  392,  391,
      390,  389,  388,  387,  385,  384,  383,  382,  381,  380,
      379,  377,  373,  372,  371,  369,  368,  367,  365,  364,
      363,  362,  360,  355,  354,  353,  351,  349,  347,  346,
      344,  343,  342,  339,  338,  335,  333,  331,  329,  328,
      326,  324,  323,  322,  321,  318,  316,  315,  314,  313,
      312,  311,  310,  308,  304,  303,  301,  299,  298,  296,

      295,  294,  293,  292,  291,  290,  288,  287,  285,  282,
      280,  279,  278,  276,  275,  274,  273,  272,  271,  270,
      269,  267,  265,  264,  263,  262,  260,  259,  258,  257,
      256,  255,  254,  253,  252,  251,  250,  249,  248,  247,
      245,  244,  243,  242,  241,  240,  239,  238,  237,  236,
      235,  234,  233,  232,  231,  230,  229,  228,  227,  225,
      224,  223,  222,  221,  220,  219,  218,  216,  215,  211,
      210,  209,  208,  206,  205,  202,  201,  200,  198,  197,
      196,  194,  192,  191,  190,  188,  186,  185,  184,  183,
      182,  181,  180,  178,  177,  176,  175,  174,  173,  172,

      171,  170,  169,  167,  166,  165,  164,  162,  161,  160,
      159,  158,  156,  154,  153,  152,  150,  149,  145,  143,
      142,  141,  140,  139,  137,  135,  132,  131,  129,  128,
      127,  125,  124,  123,  122,  120,  119,  118,  117,  116,
      115,  113,  111,  109,  108,  107,  106,  105,  100,   99,
       95,   93,   92,   90,   89,   88,   87,   86,   85,   83,
       80,   79,   78,   77,   75,   74,   73,   72,   71,   69,
       68,   67,   66,   64,   62,   61,   60,   59,   57,   56,
       53,   51,   50,   49,   44,   42,   39,   35,   30,   26,
       21,   18,   17,   16,   15,   14,   13,   12,   10,    9,

        8,    3,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568,  568,
      568,  568,  568,  568,  568,  568,  568,  568,  568
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "jive.l"
#line 9 "jive.l"
	char buf[128];
	extern char *cbjs, *cbjt;
	extern int cbjl;

#undef inputx
#define inputx()		cbjin()
#undef unputx
#define unputx(x)	cbjun(x)

void cbjun(int c);
void produce(char *s);

#line 790 "jive.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 23 "jive.l"

#line 974 "jive.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 569 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 603 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 24 "jive.l"
produce(" stash");
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 25 "jive.l"
produce(" t'row");
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 26 "jive.l"
produce(" honky code");
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 27 "jive.l"
produce(" Isaac");
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 28 "jive.l"
produce(" slow mo-fo");
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 29 "jive.l"
produce(" that slow mo-fo");
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 30 "jive.l"
produce(" snatch'd");
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 31 "jive.l"
produce(" wet-back");
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 32 "jive.l"
produce(" wet-back");
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 33 "jive.l"
produce(" greaser");
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 34 "jive.l"
produce(" greaser");
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 35 "jive.l"
produce(" snatch");
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 36 "jive.l"
produce(" duzn't");
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 37 "jive.l"
produce(" JIBE");
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 38 "jive.l"
produce(" honkyfool");
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 39 "jive.l"
produce(" doodad");
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 40 "jive.l"
produce("e da damn ");
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 41 "jive.l"
produce("a da damn ");
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 42 "jive.l"
produce("t da damn ");
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 43 "jive.l"
produce("d da damn ");
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 44 "jive.l"
produce(" dude ");
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 45 "jive.l"
produce("mama");
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 46 "jive.l"
produce("goat");
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 47 "jive.l"
produce("sump'n");
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 48 "jive.l"
produce(" honky jibe ");
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 49 "jive.l"
produce(" -on rebound- ");
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 50 "jive.l"
produce(" -check y'out latah-");
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 51 "jive.l"
{ sprintf(buf, "%s  Sheeeiit.",yytext); produce(buf); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 52 "jive.l"
{ sprintf(buf, "%s  What it is, Mama!",yytext); produce(buf); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 53 "jive.l"
{ sprintf(buf, "%s  Ya' know?",yytext); produce(buf); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 54 "jive.l"
{ sprintf(buf, "%s  'S coo', bro.",yytext); produce(buf); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 55 "jive.l"
{ sprintf(buf, "%s  Ah be baaad...",yytext); produce(buf); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 56 "jive.l"
{ sprintf(buf, "%s  Man!",yytext); produce(buf); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 57 "jive.l"
{ sprintf(buf, "%s  Slap mah fro!",yytext); produce(buf); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 58 "jive.l"
produce("Sho' nuff");
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 59 "jive.l"
produce("sho' nuff");
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 60 "jive.l"
produce(" git");
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 61 "jive.l"
produce("gots'ta");
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 62 "jive.l"
produce("gots'ta ");
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 63 "jive.l"
produce("gots'ta");
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 64 "jive.l"
produce("I's gots'ta be");
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 65 "jive.l"
produce("aint");
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 66 "jive.l"
produce("aint");
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 67 "jive.l"
produce("aint");
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 68 "jive.l"
produce(" is yo'");
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 69 "jive.l"
produce(" you is");
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 70 "jive.l"
produce(" fedora ");
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 71 "jive.l"
produce(" kicker");
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 72 "jive.l"
produce("aint");
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 73 "jive.l"
produce("gots'ta");
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 74 "jive.l"
produce("gots'");
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 75 "jive.l"
produce(" gots'ta");
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 76 "jive.l"
produce("mosey on down");
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 77 "jive.l"
produce(" mosey on down ");
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 78 "jive.l"
produce(".  Right On!  ");
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 79 "jive.l"
produce("steal");
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 80 "jive.l"
produce(" wheels ");
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 81 "jive.l"
produce("roll");
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 82 "jive.l"
produce(" feed da bud ");
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 83 "jive.l"
produce(" brother ");
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 84 "jive.l"
produce(" brother");
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 85 "jive.l"
produce("honky");
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 86 "jive.l"
produce(" gentleman ");
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 87 "jive.l"
produce("supa' fine");
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 88 "jive.l"
produce("sucka'");
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 89 "jive.l"
produce("dojigger");
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 90 "jive.l"
produce(" alley");
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 91 "jive.l"
produce("clunker");
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 92 "jive.l"
produce("o'");
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 93 "jive.l"
produce("hosed");
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 94 "jive.l"
produce("guv'ment");
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 95 "jive.l"
produce("knowed");
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 96 "jive.l"
produce("a'cuz");
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 97 "jive.l"
produce("A'cuz");
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 98 "jive.l"
produce("yo'");
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 99 "jive.l"
produce("Yo'");
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 100 "jive.l"
produce("foe");
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 101 "jive.l"
produce("gots");
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 102 "jive.l"
produce("ain't");
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 103 "jive.l"
produce("yung");
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 104 "jive.l"
produce("ya'");
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 105 "jive.l"
produce("You's");
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 106 "jive.l"
produce("fust");
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 107 "jive.l"
produce("honky pigs");
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 108 "jive.l"
produce(" chittlin'");
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 109 "jive.l"
produce(" eyeball");
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 110 "jive.l"
produce("scribble");
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 111 "jive.l"
produce("d");
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 112 "jive.l"
produce("D");
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 113 "jive.l"
produce("in'");
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 114 "jive.l"
produce(" some ");
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 115 "jive.l"
produce(" t'");
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 116 "jive.l"
produce("shun");
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 117 "jive.l"
produce(" mos' ");
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 118 "jive.l"
produce(" fum");
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 119 "jive.l"
produce(" cuz' ");
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 120 "jive.l"
produce("youse");
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 121 "jive.l"
produce("Youse");
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 122 "jive.l"
produce("coo'");
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 123 "jive.l"
produce("coo'");
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 124 "jive.l"
produce("a' ");
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 125 "jive.l"
produce("knode");
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 126 "jive.l"
produce("wants'");
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 127 "jive.l"
produce("whup'");
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 128 "jive.l"
produce("'sp");
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 129 "jive.l"
produce("'s");
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 130 "jive.l"
produce(" 's");
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 131 "jive.l"
produce(" 'es");
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 132 "jive.l"
produce("likes");
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 133 "jive.l"
produce("dun did");
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 134 "jive.l"
produce("kind'a");
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 135 "jive.l"
produce("honky chicks");
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 136 "jive.l"
produce(" dudes ");
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 137 "jive.l"
produce(" dudes ");
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 138 "jive.l"
produce(" dude ");
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 139 "jive.l"
produce("honky chick");
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 140 "jive.l"
produce("wasted");
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 141 "jive.l"
produce("baaaad");
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 142 "jive.l"
produce("jimmey ");
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 143 "jive.l"
produce("jimmey'd ");
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 144 "jive.l"
produce(" real");
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 145 "jive.l"
produce("puh'");
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 146 "jive.l"
produce("puh'");
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 147 "jive.l"
produce(" kin");
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 148 "jive.l"
produce("plum ");
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 149 "jive.l"
produce(" recon'");
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 150 "jive.l"
produce("wuz");
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 151 "jive.l"
produce(" wuz");
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 152 "jive.l"
produce(" mah'");
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 153 "jive.l"
produce(" ah' ");
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 154 "jive.l"
produce("meta-fuckin'");
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 155 "jive.l"
produce("fro");
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 156 "jive.l"
produce("rappin");
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 157 "jive.l"
produce("rap");
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 158 "jive.l"
produce("beat");
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 159 "jive.l"
produce("hoop");
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 160 "jive.l"
produce("ball");
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 161 "jive.l"
produce("homey");
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 162 "jive.l"
produce("farm");
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 163 "jive.l"
produce("Man");
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 164 "jive.l"
produce("wanna");
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 165 "jive.l"
produce("be hankerin' aftah");
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 166 "jive.l"
produce("sheeit");
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 167 "jive.l"
produce("Sheeit");
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 168 "jive.l"
produce("big-ass");
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 169 "jive.l"
produce("bad-ass");
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 170 "jive.l"
produce("little-ass");
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 171 "jive.l"
produce("radical");
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 172 "jive.l"
produce(" be ");
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 173 "jive.l"
produce("booze");
	YY_BREAK
case 151:
YY_RULE_SETUP
#line 174 "jive.l"
produce("scribblin'");
	YY_BREAK
case 152:
YY_RULE_SETUP
#line 175 "jive.l"
produce("issue of GQ");
	YY_BREAK
case 153:
YY_RULE_SETUP
#line 176 "jive.l"
produce("sheet");
	YY_BREAK
case 154:
YY_RULE_SETUP
#line 177 "jive.l"
produce(" down ");
	YY_BREAK
case 155:
YY_RULE_SETUP
#line 178 "jive.l"
produce("waaay down");
	YY_BREAK
case 156:
YY_RULE_SETUP
#line 179 "jive.l"
produce("boogie");
	YY_BREAK
case 157:
YY_RULE_SETUP
#line 180 "jive.l"
produce("'Sup, dude");
	YY_BREAK
case 158:
YY_RULE_SETUP
#line 181 "jive.l"
produce("pink Cadillac");
	YY_BREAK
case 159:
YY_RULE_SETUP
#line 182 "jive.l"
produce(yytext);
	YY_BREAK
case 160:
/* rule 160 can match eol */
YY_RULE_SETUP
#line 183 "jive.l"
produce("\n");
	YY_BREAK
case 161:
YY_RULE_SETUP
#line 185 "jive.l"
ECHO;
	YY_BREAK
#line 1863 "jive.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 569 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 569 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 568);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 185 "jive.l"



cbjin()
{
	return( *(cbjs++) );
}

void cbjun(c)
int c;
{
	*(--cbjs) = c;
}

void produce( s )
char *s;
{
	if( (strlen(cbjt) + strlen(s)) < cbjl )
		strcat( cbjt, s );
}

void do_jive(char *in, char *out, int maxlen)
{
    cbjl = maxlen;
    cbjs = in;
    cbjt = out;
    *cbjt = 0;

    yy_scan_string(in);
    yylex();

    *(cbjt+maxlen) = 0;
}


